version: '3.9'
services:

  selenium-chrome-0:
    image: seleniarm/standalone-chromium:124.0
    shm_size: "2gb"
    environment:
      - SE_NODE_SESSION_TIMEOUT=30
      - SE_NODE_REQUEST_TIMEOUT=30
      - SE_SESSION_RETRY_INTERVAL=5
    cpus: 2
    ports:
      - "4444:4444"
